### ISSUE TITLE
Price input type letter in mozilla 

### ISSUE THREAD

**Issue by H91011** [GokhanCerk/Expenses-Dashboard#6]
![Screenshot-from-2021-08-19-23-16-23.png](https://www.resimupload.org/images/2021/08/19/Screenshot-from-2021-08-19-23-16-23.png)

**Comment by GokhanCerk** [comment]
> The input type number is not supported yet in Firefox or IE9 (almost in IE10)


[input type number not working in firefox ](https://stackoverflow.com/questions/17976393/html5-input-type-number-not-working-in-firefox)

**Comment by GokhanCerk** [comment]
[input type number not working in firefox issue fix](https://github.com/GokhanCerk/Expenses-Dashboard/commit/8dd1a5e1d38cbd81583b1908bbc80ffdfc131dc0)
